from __future__ import annotations


DEFAULT_WALKING_M_PER_SEC = 1.1
DEFAULT_DIAGRAM_WALK_SECONDS_PER_UNIT = 1.3
SUBWAY_SPEED_KM_PER_H = 80.0
SUBWAY_SPEED_M_PER_SEC = SUBWAY_SPEED_KM_PER_H * 1000.0 / 3600.0
